ARG GO_VERSION=1.23.0
FROM golang:${GO_VERSION} AS build

COPY go.mod .
COPY go.sum .

RUN go mod download -x

COPY . .

RUN CGO_ENABLED=0 go build -o /bin/server .

FROM alpine:latest AS final

RUN --mount=type=cache,target=/var/cache/apk \
    apk --update add \
        ca-certificates \
        tzdata \
        && \
        update-ca-certificates

ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser
USER appuser

COPY --from=build /bin/server /bin/
COPY templates/ /templates/

EXPOSE 8080

ENTRYPOINT [ "/bin/server" ]