services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: final
    environment:
      FLAGOPS_REDIS_URI: redis://redis/
      FLAGOPS_POSTGRES_DB_DSN: postgresql://flagops:password@psql/flagops
      FLAGOPS_FACT_PROVIDER: redis
      FLAGOPS_SECRET_PROVIDER: asm
    env_file:
      - .env.local
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
      psql:
        condition: service_healthy
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
  psql:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: flagops
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5