services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: final
    environment:
      REDIS_URI: redis://redis/
    env_file:
      - .env.local
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]